version: '3.8'
services:
  taskmanagement-app: 
    build: .
    container_name: taskmanagement-app
    ports: 
      - "8082:8081"
    networks: 
      - taskmanagement-network
  mysql-db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: taskmanagementdb
    ports:
      - "3307:3306"
    volumes: 
      - mysql-data:/var/lib/mysql
    networks:
      - taskmanagement-network
volumes:
  mysql-data:

networks:
  taskmanagement-network:
    driver: bridge
